version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: WebApi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    depends_on:
      - eshop-db

  eshop-db:
    image: postgres:latest
    container_name: Database
    environment:
      - POSTGRES_DB=eshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  eshop-mq:
    image: rabbitmq:3.11.7-management
    container_name: Queue
    hostname: eshop-queue
    volumes:
      - ./.containers/rabbitmq/data/:/var/lib/rabbitmq
      - ./.containers/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest